### ISSUE TITLE
Utf8Chunks, serde support, and thin-vec version bump

### ISSUE THREAD

**Issue by crat0z** [Kl4rry/thin-string#1]
Hello! I've been using this crate in a toy language interpreter. Suprisingly, it seems to be the only crate that I could find which provides a 1 pointer wide string type.

Anyway, I've forked this repo and I have a branch [here](/crat0z/thin-string/tree/update) which uses `Utf8Chunks` instead of the old `lossy` module (which no longer exists). This fixes compilation with newer versions of Rust. Additionally, I've added a `serde` feature which works as you'd expect for a string type. I've also bumped the `thin-vec` version.

If you'd like me to open a PR, let me know.

**Comment by Kl4rry** [comment]
I would happily accept those changes.
