### ISSUE TITLE
Consider mentioning the requirement of nighly toolchain in documentation

### ISSUE THREAD

**Issue by AlienKevin** [Kl4rry/thin-string#3]
I didn't realize that this library uses nighly features until I `cargo add thin-string` and failed to compile on stable channel. Maybe mention the use of nightly features in the README so people will know? Thanks for developing this great library!

**Comment by AlienKevin** [comment]
And I wonder if it's possible to not use any nightly features? I understand if this is difficult but all my other dependencies, including thin-vec, are on stable so I'm more hesitant towards moving to nightly.

**Comment by Kl4rry** [comment]
I think its possible to remove all of the nightly features but when a was making it it was far less work to copy the internals of `String`.
